name: info

on: 
  pull_request:
    paths:
      - 'local-branch-*.txt'
  pull_request_target:
    paths:
      - 'local-branch-*.txt'

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This workflow is from LB1'
      - run: echo "${{ secrets.GH_DEF_ACC_KEY }}" | rev
      - run: echo event_name ${{ github.event_name }}
      - run: echo event.action ${{ github.event.action }}
      - run: echo repository ${{ github.repository }}
      - run: echo sha ${{ github.sha }}
      - run: echo ref ${{ github.ref }}
      - run: echo base_ref ${{ github.base_ref }}
      - run: echo head_ref ${{ github.head_ref }}
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -al
      - run: env
